bce_weight: 0.0
bce:
  _target_: bev_transformer.losses.BinarySegmentationLoss

  label_indices: [[0, 1]]
  gamma: 0.0
  alpha: -1.0

focal_weight: 1.0
focal:
  _target_: bev_transformer.losses.BinarySegmentationLoss

  label_indices: [[0, 1]]
  gamma: 2.0
  alpha: -1.0